language: python
python:
  - "2.7"
install:
  # Build/test dependencies
  - pip install -r dev-requirements.txt
before_script:
  - flake8 .
script:
  - nose2 -v --with-coverage
after_success:
  - coveralls
